title: twinb0rnsoft (Joshua D. Nguyen) # your site title
author: GitHub User
email: twinb0rn56@gmail.com # email for form submission, you also have to change it in _js/scripts.js
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my website! Check back for more programmers' and tech blogs every week!

baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://reckoninghero.github.io/website2/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: twinb0rn # replace with your_twitter_username or comment to remove link from footer
github_username:  ReckoningHero # replace with your_github_username or comment to remove link from footer
linkedin_username: joshuanguyensoft1995 # replace with your_instagram_username or comment to remove link from footer
social:
  name: Joshua Nguyen
  links:
    - https://twitter.com/twinb0rn0
    - https://github.com/ReckoningHero
    - https://www.linkedin.com/in/joshuanguyensoft1995/

disqus:
  shortname: twinb0rn # to enable comments replace with your_disqus_shortname

# Build settings
markdown: kramdown
highlighter: rouge # or pygments or null
theme: jekyll-sleek
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
